### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [osmank3/otp-keys#4]
Where do you store the otp ?

**Comment by osmank3** [comment]
Secret codes stored in GSettings at /org/gnome/shell/extensions/otp-keys address.

**Comment by dlastov** [comment]
I can't find it (gsettings get says: 'No such schema “org.gnome.shell.extensions.otp-keys”').
But first of all, this kind of data should be rather in the keyring?

**Comment by osmank3** [comment]
@dlastov It is not shown because the scheme is not system wide installed. You can see it with dconf editor.
GSettings user configurations are stored in ~/.config/dconf/user and that folder permission only user can read-write(700). This permission is enough I guess. Maybe I will move secrets to keyring in the future, not sure.
